//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopThu
    {
        public int HopThuID { get; set; }
        public string Hoten { get; set; }
        public string Email { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public bool DaDoc { get; set; }
        public string SDT { get; set; }
        public string TieuDe { get; set; }
    }
}
