//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DatHangCTs = new HashSet<DatHangCT>();
        }
    
        public int SanPhamID { get; set; }
        public string TenSanPham { get; set; }
        public string MoTa { get; set; }
        public int DonGia { get; set; }
        public int GiaKM { get; set; }
        public string Hinh { get; set; }
        public int NhomspID { get; set; }
        public System.DateTime NgayCapNhat { get; set; }
        public bool NgungBan { get; set; }
        public string BiDanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatHangCT> DatHangCTs { get; set; }
        public virtual Nhomsp Nhomsp { get; set; }
    }
}
